language: elixir
sudo: false

elixir: '1.10.3'
otp_release: '21.1'

stages:
  - check formatted
  - test

jobs:
  include:
    - stage: test

    - elixir: '1.7.0'
      otp_release: '20.3'

    - stage: check formatted
      script: mix format --check-formatted

notifications:
  recipients:
    - jose.valim@plataformatec.com.br
    - gazler@gmail.com
